In [1]:
import numpy as np
import tensorflow as tf
from keras.activations import relu
tf.enable_eager_execution()

# 邻接矩阵 包含了四个点
A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float)

# 每个点包含的特征
x = np.matrix([
    [i, -i]
    for i in range(A.shape[0])], dtype=float)
# print(x)
# [[ 0.  0.]
#  [ 1. -1.]
#  [ 2. -2.]
#  [ 3. -3.]]

print(A*x) # 得到的是当前vertex的所有邻居节点的特征之和,
# ,换句话说，图卷积层将每个节点表示为其相邻节点的聚合 当然这里仅仅是使用了邻接矩阵
# 节点的聚合表征不包含它自己的特征！该表征是相邻节点的特征聚合，因此只有具有自环（self-loop）的节点才会在该聚合中包含自己的特征 [1]。
# [[ 1. -1.]
#  [ 5. -5.]
#  [ 1. -1.]
#  [ 2. -2.]]

## 添加自环解决自z身特征无法融入问题
I = np.matrix(np.eye(A.shape[0]))

A_Hat = A + I
print(A_Hat)
# [[1. 1. 0. 0.]
#  [0. 1. 1. 1.]
#  [0. 1. 1. 0.]
#  [1. 0. 1. 1.]]


Using TensorFlow backend.


[[ 1. -1.]
 [ 5. -5.]
 [ 1. -1.]
 [ 2. -2.]]
[[1. 1. 0. 0.]
 [0. 1. 1. 1.]
 [0. 1. 1. 0.]
 [1. 0. 1. 1.]]


In [2]:
A_Hat * x # 现在，由于每个节点都是自己的邻居，每个节点在对相邻节点的特征求和过程中也会囊括自己的特征！

matrix([[ 1., -1.],
        [ 6., -6.],
        [ 3., -3.],
        [ 5., -5.]])

In [3]:
#通过将邻接矩阵 A 与度矩阵 D 的逆相乘，对其进行变换

In [4]:
# 得到节点的度
D = np.array(np.sum(A, axis=0))[0]


In [5]:
D

array([1., 2., 2., 1.])

In [6]:
# 得到对角矩阵
D = np.matrix(np.diag(D)) 


In [7]:
D**-1*A 
# 可以发现邻接矩阵 的每个值都除以了该点的度，这样进行了归一化


matrix([[0. , 1. , 0. , 0. ],
        [0. , 0. , 0.5, 0.5],
        [0. , 0.5, 0. , 0. ],
        [1. , 0. , 1. , 0. ]])

In [8]:
D**-1*A*x # 将变换应用于x

matrix([[ 1. , -1. ],
        [ 2.5, -2.5],
        [ 0.5, -0.5],
        [ 2. , -2. ]])

In [9]:
D_Hat = np.array(np.sum(A_Hat, axis=0))[0]
D_Hat = np.matrix(np.diag(D_Hat))
D_Hat

matrix([[2., 0., 0., 0.],
        [0., 3., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 2.]])

In [10]:
W = np.matrix([[1, -1],  # 权重
             [-1, 1]])



In [13]:
# 这就是一个带有邻接矩阵、
# 输入特征、权重和激活函数的完整隐藏层！
out = relu(D_Hat**-1 * A_Hat * x * W)


In [12]:
for i in enumerate(out):
    print(i)


(0, <tf.Tensor: id=6, shape=(2,), dtype=float64, numpy=array([1., 0.])>)
(1, <tf.Tensor: id=11, shape=(2,), dtype=float64, numpy=array([4., 0.])>)
(2, <tf.Tensor: id=16, shape=(2,), dtype=float64, numpy=array([2., 0.])>)
(3, <tf.Tensor: id=21, shape=(2,), dtype=float64, numpy=array([5., 0.])>)


In [14]:
from networkx import to_numpy_matrix
zkc = karate_club_graph()
order = sorted(list(zkc.nodes()))
A = to_numpy_matrix(zkc, nodelist=order)
I = np.eye(zkc.number_of_nodes())
A_hat = A + I
D_hat = np.array(np.sum(A_hat, axis=0))[0]
D_hat = np.matrix(np.diag(D_hat))

NameError: name 'karate_club_graph' is not defined